# Generated by Django 5.0.3 on 2026-05-26 19:58

import ckeditor.fields
import django.db.models.deletion
import embed_video.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/portadas/', verbose_name='Imagen de portada')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_impartidos', to=settings.AUTH_USER_MODEL, verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-creado_en'],
                'permissions': [('puede_ver_todos_cursos', 'Puede ver todos los cursos'), ('puede_asignar_instructores', 'Puede asignar instructores')],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrito_en', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito el')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('certificado_generado', models.BooleanField(default=False, verbose_name='Certificado generado')),
                ('progreso', models.PositiveSmallIntegerField(default=0, verbose_name='Progreso (%)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='courses.curso', verbose_name='Curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='URL del video')),
                ('orden', models.PositiveIntegerField(verbose_name='Orden')),
                ('vista_previa_gratis', models.BooleanField(default=False, verbose_name='Vista previa gratuita')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='courses.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('estudiante', 'curso'), name='unique_estudiante_curso'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.CheckConstraint(check=models.Q(('progreso__gte', 0), ('progreso__lte', 100)), name='progreso_entre_0_y_100'),
        ),
        migrations.AddConstraint(
            model_name='leccion',
            constraint=models.UniqueConstraint(fields=('curso', 'orden'), name='unique_orden_por_curso'),
        ),
    ]
