# Generated by Django 5.0.3 on 2026-06-03 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeccionCompletada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada_en', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones_completadas', to='courses.inscripcion')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completada_por', to='courses.leccion')),
            ],
            options={
                'verbose_name': 'Lección completada',
                'verbose_name_plural': 'Lecciones completadas',
                'unique_together': {('inscripcion', 'leccion')},
            },
        ),
    ]
