# Generated by Django 5.0.3 on 2026-06-09 05:29

import ckeditor.fields
import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_leccioncompletada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leccion',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='video',
        ),
        migrations.AlterField(
            model_name='leccion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='courses.curso'),
        ),
        migrations.CreateModel(
            name='RecursoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto / Lectura'), ('video', 'Video Embebido'), ('archivo', 'Documento Descargable (PDF/Word)'), ('audio', 'Audio (MP3/Podcast)')], max_length=10)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('contenido_texto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('video_url', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='lecciones/recursos/')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='courses.leccion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
