# Generated by Django 5.0.3 on 2025-06-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_testdomino_resultadodomino_problemadomino'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadodomino',
            name='baremo',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resultadodomino',
            name='diagnostico',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resultadodomino',
            name='eficiencia',
            field=models.FloatField(default=0.0),
        ),
    ]
