# Generated by Django 5.0.3 on 2025-06-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_resultadodomino_baremo_resultadodomino_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadodomino',
            name='grupo_edad',
            field=models.CharField(default='general', max_length=20),
        ),
    ]
